repos:
  -   id: check-added-large-files
      name: check for added large files
      description: prevents giant files from being committed.
      entry: check-added-large-files
      language: python
      stages: [pre-commit, pre-push, manual]
      minimum_pre_commit_version: 3.2.0
  -   id: check-ast
      name: check python ast
      description: simply checks whether the files parse as valid python.
      entry: check-ast
      language: python
      types: [python]
  -   id: check-case-conflict
      name: check for case conflicts
      description: checks for files that would conflict in case-insensitive filesystems.
      entry: check-case-conflict
      language: python
      minimum_pre_commit_version: 3.2.0
  -   id: check-json
      name: check json
      description: checks json files for parseable syntax.
      entry: check-json
      language: python
      types: [json]
  -   id: pretty-format-json
      name: pretty format json
      description: sets a standard for formatting json files.
      entry: pretty-format-json
      language: python
      types: [json]
  -   id: check-symlinks
      name: check for broken symlinks
      description: checks for symlinks which do not point to anything.
      entry: check-symlinks
      language: python
      types: [symlink]
  -   id: check-toml
      name: check toml
      description: checks toml files for parseable syntax.
      entry: check-toml
      language: python
      types: [toml]
  -   id: check-yaml
      name: check yaml
      description: checks yaml files for parseable syntax.
      entry: check-yaml
      language: python
      types: [yaml]
  -   id: debug-statements
      name: debug statements (python)
      description: checks for debugger imports and py37+ `breakpoint()` calls in python source.
      entry: debug-statement-hook
      language: python
      types: [python]
      stages: [pre-commit, pre-push, manual]
  -   id: detect-aws-credentials
      name: detect aws credentials
      description: detects *your* aws credentials from the aws cli credentials file.
      entry: detect-aws-credentials
      language: python
      types: [text]
  -   id: detect-private-key
      name: detect private key
      description: detects the presence of private keys.
      entry: detect-private-key
      language: python
      types: [text]
  -   id: double-quote-string-fixer
      name: fix double quoted strings
      description: replaces double quoted strings with single quoted strings.
      entry: double-quote-string-fixer
      language: python
      types: [python]
  -   id: end-of-file-fixer
      name: fix end of files
      description: ensures that a file is either empty, or ends with one newline.
      entry: end-of-file-fixer
      language: python
      types: [text]
      stages: [pre-commit, pre-push, manual]
      minimum_pre_commit_version: 3.2.0
  -   id: mixed-line-ending
      name: mixed line ending
      description: replaces or checks mixed line ending.
      entry: mixed-line-ending
      language: python
      types: [text]
  -   id: trailing-whitespace
      name: trim trailing whitespace
      description: trims trailing whitespace.
      entry: trailing-whitespace-fixer
      language: python
      types: [text]
      stages: [pre-commit, pre-push, manual]
      minimum_pre_commit_version: 3.2.0
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
